# Generated by Django 4.2.7 on 2023-12-15 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('event', models.CharField(choices=[('S', 'siembra'), ('T', 'trasplante'), ('C', 'Cosecha'), ('R', 'riego'), ('F', 'fumigacion'), ('P', 'poda')], max_length=1)),
                ('estacion', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Huerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', location_field.models.plain.PlainLocationField(max_length=63)),
                ('sitio', models.CharField(choices=[('M', 'maceta'), ('J', 'jardin'), ('T', 'terraza'), ('P', 'parcela')], max_length=1)),
                ('sustrato', models.CharField(choices=[('ARE', 'arenoso'), ('ARC', 'arcilloso'), ('LIM', 'limoso'), ('FRA', 'franco'), ('TUR', 'turbado')], max_length=3)),
                ('area', models.FloatField(blank=True, null=True)),
                ('acidez', models.FloatField(blank=True, null=True)),
                ('abonado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('V', 'virico'), ('B', 'bacteriano'), ('F', 'fungico'), ('A', 'animal'), ('P', 'vegetal')], max_length=1)),
                ('descripcion', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HE', 'herbacea'), ('AL', 'árbol'), ('AO', 'arbusto')], max_length=2)),
                ('ciclo', models.CharField(choices=[('A', 'anual'), ('B', 'bianual'), ('P', 'perenne')], max_length=1)),
                ('nombre_comun', models.CharField(db_column='nombre', max_length=20)),
                ('nombre_cientifico', models.CharField(max_length=30)),
                ('phmax', models.FloatField()),
                ('phmin', models.FloatField()),
                ('epoca_siembra', models.DateField(db_column='siembra', default=django.utils.timezone.now)),
                ('tiempo_trasplante', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('horas_luz', models.IntegerField()),
                ('demanda_hidrica', models.FloatField(blank=True, null=True)),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Huerto.huerto')),
            ],
        ),
        migrations.CreateModel(
            name='Planta_regada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Huerto.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(default=django.utils.timezone.now)),
                ('puntuacion', models.IntegerField()),
                ('comentarios', models.TextField(max_length=2000)),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huerto_voto', to='Huerto.huerto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_voto', to='Huerto.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=150)),
                ('consejos', models.TextField(max_length=1000)),
                ('aplicacion', models.TextField(max_length=200)),
                ('plaga', models.ManyToManyField(to='Huerto.plaga')),
            ],
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('A', 'agua'), ('F', 'fertilizante'), ('L', 'lluvia'), ('P', 'plaguicida')], max_length=1)),
                ('planta', models.ManyToManyField(through='Huerto.Planta_regada', to='Huerto.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promocion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('descuento', models.IntegerField()),
                ('fecha_promocion', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Huerto.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='planta_regada',
            name='riego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Huerto.riego'),
        ),
        migrations.AddField(
            model_name='plaga',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Huerto.planta'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=2000)),
                ('fecha_incidencia', models.DateField(db_column='fecha', default=django.utils.timezone.now)),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huerto_incidencia', to='Huerto.huerto')),
            ],
        ),
        migrations.AddField(
            model_name='huerto',
            name='usuario',
            field=models.ManyToManyField(related_name='usuario_huerto', to='Huerto.usuario'),
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(max_length=2000)),
                ('plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaga_plant', to='Huerto.plaga')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramientas', models.FloatField()),
                ('facturas', models.FloatField()),
                ('imprevistos', models.FloatField()),
                ('Descripcion', models.TextField(max_length=2000)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gasto', to='Huerto.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Fruto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('planta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Huerto.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=2000)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Huerto.calendario')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Huerto.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Contrasenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasenha', models.CharField(max_length=30)),
                ('ultima_modificacion', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Huerto.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='calendario',
            name='Planta',
            field=models.ManyToManyField(through='Huerto.Evento', to='Huerto.planta'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.CharField(choices=[('C', 'comentario'), ('N', 'noticia'), ('E', 'enlace'), ('T', 'tutorial'), ('R', 'reseña')], max_length=1)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('etiqueta', models.CharField(max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_blog', to='Huerto.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('C', 'Caixa'), ('B', 'BBVA'), ('U', 'Unicaja'), ('I', 'ING')], max_length=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_banco', to='Huerto.usuario')),
            ],
        ),
    ]
