# Generated by Django 3.2.22 on 2023-11-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Huerto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='huerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huerto_incidencia', to='Huerto.huerto'),
        ),
    ]
